name: CI - gh-pages - Step 2 - Build and deploy to gh-pages

on:
  push:
    branches: [release/gh-pages]

jobs:
  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: 🚚 Get latest code (checkout repo)
        uses: actions/checkout@v4

      - name: Replace scss variable properties
        run: cp -f ${GITHUB_WORKSPACE}/src/environments/gh-pages/variables.scss ${GITHUB_WORKSPACE}/src/environments/variables.scss

      - name: Rename environment-example.ts file to environment.ts
        run: |
          mv src/environments/environment-example.ts src/environments/environment.ts

      - name: Replace config in environment.ts
        run: |
          sed -i "s/FIREBASE_API_KEY/${{ secrets.FIREBASE_API_KEY }}/g" src/environments/gh-pages/environment.ts

      - name: Replace build version in environment.ts
        run: |
          BUILD_VERSION=$(date +'%Y%m%d%H%M%S')
          sed -i "s/BUILD_VERSION_TEMPLATE/${BUILD_VERSION}/g" src/environments/gh-pages/environment.ts

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npm install

      - name: 🔨 Build with gh-pages settings
        run: npm run build-gh-pages

      - name: Copy custom 404 page for GitHub pages
        run: cp ${GITHUB_WORKSPACE}/src/environments/gh-pages/404.html ${GITHUB_WORKSPACE}/docs/browser/404.html

      - name: Update last deployment data and time
        run: sed -i "s/DD-MM-YYYY HH:MM:SS/$(TZ=Europe/Warsaw date +'%d-%m-%Y %H:%M:%S')/g" ${GITHUB_WORKSPACE}/docs/browser/assets/status/status.json

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs/browser

  deploy:
    needs: build
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
      contents: read
    steps:
      - name: 📂 Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact-path: ./docs/browser
