name: CI - firebase - Step 3 - Build and deploy to firebase-functions

on:
  workflow_dispatch:

jobs:
  deploy_functions:
    name: Deploy Cloud Functions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WORD_CHECKER_APP_2CBFD }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies for Functions
        run: npm install
        working-directory: functions

      - name: 🎉 Deploy Cloud Functions
        run: firebase deploy --only functions --project word-checker-app-2cbfd
